name: get_event_bus
description: A minimal and scalable light-weight event bus library for get.dart
version: 0.1.0
homepage: https://github.com/rua-flutter/get_event_bus.dart

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ">=4.0.0 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
